### ISSUE TITLE
Metadata extract

### ISSUE THREAD

**Issue by ptichalouf** [imagegenius/docker-immich#10]
error with metadata extractor 

`[Nest] 141  - 01/22/2023, 8:27:09 AM   ERROR [MetadataExtractionProcessor] Error extracting EXIF QueryFailedError: invalid input syntax for type integer: "100, 0, 0"
QueryFailedError: invalid input syntax for type integer: "100, 0, 0"
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/app/immich/server/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/app/immich/server/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/app/immich/server/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/app/immich/server/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
    at async MetadataExtractionProcessor.extractExifInfo (/app/immich/server/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:160:13)
[Nest] 141  - 01/22/2023, 8:27:09 AM   ERROR [MetadataExtractionProcessor] Error extracting EXIF QueryFailedError: invalid input syntax for type integer: "100, 0"
QueryFailedError: invalid input syntax for type integer: "100, 0"
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/app/immich/server/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/app/immich/server/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/app/immich/server/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/app/immich/server/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
    at async MetadataExtractionProcessor.extractExifInfo (/app/immich/server/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:160:13)
[Nest] 141  - 01/22/2023, 8:27:09 AM   ERROR [MetadataExtractionProcessor] Error extracting EXIF TypeError: exposureTime.split is not a function
TypeError: exposureTime.split is not a function
    at getExposureTimeDenominator (/app/immich/server/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:113:56)
    at MetadataExtractionProcessor.extractExifInfo (/app/immich/server/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:128:36)
[Nest] 141  - 01/22/2023, 8:27:09 AM   ERROR [MetadataExtractionProcessor] Error extracting EXIF QueryFailedError: invalid input syntax for type integer: "80, 0, 0"
QueryFailedError: invalid input syntax for type integer: "80, 0, 0"
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/app/immich/server/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/app/immich/server/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/app/immich/server/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/app/immich/server/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
    at async MetadataExtractionProcessor.extractExifInfo (/app/immich/server/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:160:13)`

**Comment by hydazz** [comment]
@alextran1502, sorry to bother you, but i don't think this is an issue with this container.
Heres what chatgtp has to say about it:

> This is an error message indicating that there was an issue with a query being executed in a Postgres database. Specifically, it is saying that there is an "invalid input syntax for type integer" with the value "100, 0, 0". It appears to be occurring in the MetadataExtractionProcessor, which could be a part of some image or media processing system. It might be caused by an error in the code or data that is being passed to the query. It could also be caused by an issue with the database itself.
It is suggested to check the SQL query that is being executed, and also the data that is being passed to the query, to see if there is any issue with it. Additionally, check the database for any issues or corruption that could be causing this error.

**Comment by hydazz** [comment]
try using `ghcr.io/imagegenius/immich:v1.42.0_65-dev-ig19`, does the error persist?

**Comment by alextran1502** [comment]
Please raise the issue in the main repo. I think this is a bug in the code
