### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by travisboss** [imagegenius/docker-immich#130]
```
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/immich/machine-learning/app/main.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
^[Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/immich/machine-learning/app/main.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/immich/machine-learning/app/main.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/immich/machine-learning/app/main.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

When I view the webpage I keep getting this error in the logs, unsure what it affects or what the actual issue is?  Here is my docker compose:

```yaml
version: "2.1"
networks:
  docker-services:
    external: true
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    runtime: nvidia
    container_name: immich
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - DB_HOSTNAME=postgres14
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - CUDA_ACCELERATION=true #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /pool/datavault/immich/config:/config
      - /pool/datavault/immich/photos:/photos
      - /pool/datavault/immich/machine-learning:/config/machine-learning #optional
    ports:
      - 9088:8080
    restart: unless-stopped
    networks:
      - docker-services

# PostgreSQL 14:
  postgres14:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      PUID: 1000
      PGID: 100
      TZ: America/Chicago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /pool/datavault/immich/postgresql:/var/lib/postgresql/data
    networks:
      - docker-services
```

My GPU is a P2000 and I am using the docker nvidia-smi container.

**Comment by martabal** [comment]
@travisboss should be fixed, can you try ?

**Comment by travisboss** [comment]
@martabal sorry for the delay I thought i replied, this is in fact fixed.
