### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by modem7** [imagegenius/docker-immich#235]
Heya, 

Just trying to run the container now, but I'm getting the following error in the logs: 

```console
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding imagegenius/mods:universal-redis to container
[mod-init] Downloading imagegenius/mods:universal-redis from registry-1.docker.io
[mod-init] Installing imagegenius/mods:universal-redis
[mod-init] imagegenius/mods:universal-redis applied to container
[migrations] started
[migrations] no migrations found

╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  To support this applications developer(s) visit:
  Immich: https://immich.app/docs/overview/support-the-project
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 1000
  User GID: 999
╚═══════════════════════════════╝
**** Adding redis to package install list ****
[mod-init] **** Installing all mod packages ****
**** creating video group videoqs7q with id 110 ****
**** adding /dev/dri/renderD128 to video group videoqs7q with id 110 ****
Get:1 http://archive.ubuntu.com/ubuntu lunar InRelease [267 kB]
**** adding /dev/dri/card1 to video group video with id 44 ****
**** permissions for /dev/dri/card0 are good ****
Get:2 http://archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]
Get:3 http://archive.ubuntu.com/ubuntu lunar-security InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu lunar/multiverse Sources [352 kB]
Get:5 http://archive.ubuntu.com/ubuntu lunar/main Sources [1,697 kB]
Get:6 http://archive.ubuntu.com/ubuntu lunar/restricted Sources [29.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu lunar/universe Sources [23.3 MB]
Get:8 http://archive.ubuntu.com/ubuntu lunar/multiverse amd64 Packages [289 kB]
Get:9 http://archive.ubuntu.com/ubuntu lunar/universe amd64 Packages [18.7 MB]
Get:10 http://archive.ubuntu.com/ubuntu lunar/main amd64 Packages [1,797 kB]
Get:11 http://archive.ubuntu.com/ubuntu lunar/restricted amd64 Packages [181 kB]
Get:12 http://archive.ubuntu.com/ubuntu lunar-updates/restricted Sources [20.9 kB]
Get:13 http://archive.ubuntu.com/ubuntu lunar-updates/universe Sources [130 kB]
Get:14 http://archive.ubuntu.com/ubuntu lunar-updates/multiverse Sources [11.9 kB]
Get:15 http://archive.ubuntu.com/ubuntu lunar-updates/main Sources [222 kB]
Get:16 http://archive.ubuntu.com/ubuntu lunar-updates/multiverse amd64 Packages [7,154 B]
Get:17 http://archive.ubuntu.com/ubuntu lunar-updates/main amd64 Packages [674 kB]
Get:18 http://archive.ubuntu.com/ubuntu lunar-updates/restricted amd64 Packages [570 kB]
Get:19 http://archive.ubuntu.com/ubuntu lunar-updates/universe amd64 Packages [1,045 kB]
Get:20 http://archive.ubuntu.com/ubuntu lunar-security/main Sources [156 kB]
Get:21 http://archive.ubuntu.com/ubuntu lunar-security/universe Sources [104 kB]
Get:22 http://archive.ubuntu.com/ubuntu lunar-security/restricted Sources [20.9 kB]
Get:23 http://archive.ubuntu.com/ubuntu lunar-security/multiverse Sources [11.0 kB]
Get:24 http://archive.ubuntu.com/ubuntu lunar-security/multiverse amd64 Packages [7,154 B]
Get:25 http://archive.ubuntu.com/ubuntu lunar-security/restricted amd64 Packages [565 kB]
Get:26 http://archive.ubuntu.com/ubuntu lunar-security/universe amd64 Packages [933 kB]
Get:27 http://archive.ubuntu.com/ubuntu lunar-security/main amd64 Packages [533 kB]
Fetched 51.8 MB in 3s (19.9 MB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libatomic1 libjemalloc2 liblzf1 redis-tools
Suggested packages:
  ruby-redis
The following NEW packages will be installed:
  libatomic1 libjemalloc2 liblzf1 redis-server redis-tools
0 upgraded, 5 newly installed, 0 to remove and 6 not upgraded.
Need to get 1,504 kB of archives.
After this operation, 7,672 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu lunar-updates/main amd64 libatomic1 amd64 13.1.0-2ubuntu2~23.04 [10.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu lunar/universe amd64 libjemalloc2 amd64 5.3.0-1 [260 kB]
Get:3 http://archive.ubuntu.com/ubuntu lunar/universe amd64 liblzf1 amd64 3.6-3 [7,444 B]
Get:4 http://archive.ubuntu.com/ubuntu lunar/universe amd64 redis-tools amd64 5:7.0.8-4 [1,175 kB]
Get:5 http://archive.ubuntu.com/ubuntu lunar/universe amd64 redis-server amd64 5:7.0.8-4 [51.7 kB]
Fetched 1,504 kB in 0s (6,456 kB/s)
Selecting previously unselected package libatomic1:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 17600 files and directories currently installed.)
Preparing to unpack .../libatomic1_13.1.0-2ubuntu2~23.04_amd64.deb ...
Unpacking libatomic1:amd64 (13.1.0-2ubuntu2~23.04) ...
Selecting previously unselected package libjemalloc2:amd64.
Preparing to unpack .../libjemalloc2_5.3.0-1_amd64.deb ...
Unpacking libjemalloc2:amd64 (5.3.0-1) ...
Selecting previously unselected package liblzf1:amd64.
Preparing to unpack .../liblzf1_3.6-3_amd64.deb ...
Unpacking liblzf1:amd64 (3.6-3) ...
Selecting previously unselected package redis-tools.
Preparing to unpack .../redis-tools_5%3a7.0.8-4_amd64.deb ...
Unpacking redis-tools (5:7.0.8-4) ...
Selecting previously unselected package redis-server.
Preparing to unpack .../redis-server_5%3a7.0.8-4_amd64.deb ...
Unpacking redis-server (5:7.0.8-4) ...
Setting up libjemalloc2:amd64 (5.3.0-1) ...
Setting up liblzf1:amd64 (3.6-3) ...
Setting up libatomic1:amd64 (13.1.0-2ubuntu2~23.04) ...
Setting up redis-tools (5:7.0.8-4) ...
Setting up redis-server (5:7.0.8-4) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.37-0ubuntu2.1) ...
[custom-init] No custom files found, skipping...
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [NestFactory] Starting Nest application...
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +29ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +4ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 586  - 11/26/2023, 4:33:55 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 586  - 11/26/2023, 4:33:55 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:33:58 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:01 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:04 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:13 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:16 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:19 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 586  - 11/26/2023, 4:34:19 PM   ERROR [ExceptionHandler] could not open file "global/pg_filenode.map": Permission denied
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [NestFactory] Starting Nest application...
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +32ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +4ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1435  - 11/26/2023, 4:34:21 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 1435  - 11/26/2023, 4:34:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 1435  - 11/26/2023, 4:34:27 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 1435  - 11/26/2023, 4:34:30 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 1435  - 11/26/2023, 4:34:33 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 1435  - 11/26/2023, 4:34:36 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
error: could not open file "global/pg_filenode.map": Permission denied
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

My compose file is as follows:

```yaml
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: Immich
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DB_HOSTNAME=immichdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      # - DB_PORT=5432 #optional
      # - REDIS_PORT=6379 #optional
      # - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_WORKERS=4 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - $USERDIR/Immich:/config
      - /mnt/oldhd/Pictures:/photos
      - /mnt/immich/MachineLearning:/config/machine-learning
      - /mnt/immich/imports:/import
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    networks:
      pihole:
        ipv4_address: '172.22.0.147'
      isolated:
    ports:
      - 6431:8080
    restart: always

  immichdb:
    container_name: ImmichDB
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=immich
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      isolated:
    restart: always
    volumes:
      - $USERDIR/Immich/DB:/var/lib/postgresql/data
```

Unsure where I'm going wrong here, Docker DNS should resolve with no issues.

**Comment by modem7** [comment]
Weird. 

Recreated the folders and all is now working. 

Must have been an odd snafu.

Closing
