### ISSUE TITLE
Docker image error on Unraid with latest version v1.91.4-ig233

### ISSUE THREAD

**Issue by JSM2703** [imagegenius/docker-immich#271]
Latest version :

Fout: failed to register layer: ApplyLayer exit status 1 stdout: stderr: lchown /app/immich/server/node_modules/highlight.js/styles/foundation.css: invalid argument

**Comment by hydazz** [comment]
can you post your complete logs?

**Comment by 7eptem** [comment]
i have some other error with latest image, not sure when this happened or if this is related
`Error: 
The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.
If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
See https://immich.app/docs/guides/database-queries for how to query the database.
Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
 at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:137:19)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 at async /app/immich/server/dist/domain/database/database.service.js:39:13
at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23`

**Comment by martabal** [comment]
> i have some other error with latest image, not sure when this happened or if this is related `Error: The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases. If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it. In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser. See https://immich.app/docs/guides/database-queries for how to query the database. Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version. at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:137:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /app/immich/server/dist/domain/database/database.service.js:39:13 at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23`

You have to update your postgres docker image https://github.com/imagegenius/docker-immich/issues/254#issuecomment-1935803120

**Comment by 7eptem** [comment]
> > i have some other error with latest image, not sure when this happened or if this is related `Error: The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases. If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it. In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser. See https://immich.app/docs/guides/database-queries for how to query the database. Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version. at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:137:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /app/immich/server/dist/domain/database/database.service.js:39:13 at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23`
> 
> You have to update your postgres docker image [#254 (comment)](https://github.com/imagegenius/docker-immich/issues/254#issuecomment-1935803120)

i just did but now i have this in the logs 

`ERROR:  pgvecto.rs: The extension is upgraded so all index files are outdated.
        ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
2024-02-24 14:06:52.973 GMT [1750] STATEMENT:`

**Comment by martabal** [comment]
Please read https://github.com/immich-app/immich/releases/tag/v1.95.0

**Comment by 7eptem** [comment]
> Please read https://github.com/immich-app/immich/releases/tag/v1.95.0

i think i need more assistance, i do not use docker compose, i use unraid

i did try to add this into the console in postgres 
`BEGIN;

CREATE SCHEMA IF NOT EXISTS vectors;
ALTER DATABASE immich SET search_path TO "$user", public, vectors;
SET search_path TO "$user", public, vectors;

UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';
ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';

SELECT pgvectors_upgrade();

COMMIT;`

but i get 
`COMMIT;sh: 1: BEGIN: not found
# # sh: 3: CREATE: not found
# sh: 4: ALTER: not found
# sh: 5: SET: not found
# # sh: 7: UPDATE: not found
# sh: 8: UPDATE: not found
# sh: 9: ALTER: not found
# sh: 10: UPDATE: not found
# sh: 11: ALTER: not found
# # sh: 13: Syntax error: "(" unexpected
# # `

sorry but i dont know i can update this

**Comment by martabal** [comment]
You need to use to do in psql or in a postgres tool like dbeaver, adminer...

**Comment by bishop1978** [comment]
i had the same issue on unraid and i was replacing my postgre installation with the ones from spaceinvader:
search in the unraid community app store for "PostgreSQL_Immich".
i saw there is also an official version ... you could also try this.
