### ISSUE TITLE
WEBUI

### ISSUE THREAD

**Issue by wdellavecchia** [imagegenius/docker-immich#286]
Hi,
  I have been trying to days to get WEBUI to load and I can't figure it out. I have changed ports, reviewed settings. Nothing I do works. Can you advise at all? using Unraid

**Comment by martabal** [comment]
Can you share your docker logs ?

**Comment by wdellavecchia** [comment]
text  error  warn  system  array  login  

    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2363  - 01/19/2024, 12:28:44 PM   ERROR [ExceptionHandler] database "immich" does not exist
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [NestFactory] Starting Nest application...
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)

    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
error: database "immich" does not exist
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)

    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
error: database "immich" does not exist

    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 2392  - 01/19/2024, 12:29:10 PM   ERROR [ExceptionHandler] database "immich" does not exist
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by martabal** [comment]
You have an issue with your database. I think you're using an already existing database, if so, you have to create manually the database "immich"

**Comment by wdellavecchia** [comment]
Thank you! I downloaded postgreql14, I dont have any other database. Could there be an issue with that? i thought it was simple settings.

**Comment by wdellavecchia** [comment]
![image](https://github.com/imagegenius/docker-immich/assets/157166306/02ae2be7-65b8-4450-80c4-380d0444f803)

**Comment by martabal** [comment]
Did you change the value of `POSTGRES_DB` after downloading postgres ?

**Comment by wdellavecchia** [comment]
you know what, I think I did. I changed it to a lower case i... 

Do I need to delet database?

**Comment by martabal** [comment]
> Do I need to delet database?

If you don't use postgres, I think that's the best option. Simply stop your postgres container then run `rm -r /mnt/cache/appdata/postgresql14` in your unraid console and start again your container and you're good to go !

But you'll run in another issue : As stated in the Immich `Overview` section, you must install a custom postgres image (an image with an extension called pgvecto.rs installed). To do so, the simplest solution is to change the `Repository` value from `postgres:14` to `tensorchord/pgvecto-rs:pg14-v0.1.11`

**Comment by wdellavecchia** [comment]
it worked!!
thank you so much!!

**Comment by martabal** [comment]
Nice !

Just FYI, there's currently an issue with downloading machine learning models which should be solved [with this PR](#285).
Until it's get merged, you can add a new environment variable in your immich template such as:
- `Key`: `HF_HOME`
- `Name`: `HF_HOME`
- `Value`: `/tmp`

You can remove it once the machine-learning models have been downloaded

**Comment by martabal** [comment]
You're welcome :smile:
