### ISSUE TITLE
Smart Search Error

### ISSUE THREAD

**Issue by Nixon506E** [imagegenius/docker-immich#322]
Smart search no longer works due to an error installing insightface (numpy).

```
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  - Installing insightface (0.7.3)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
      from . import multiarray
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
      from . import overrides
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: /tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so: failed to map segment from shared object
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
      from numpy.__config__ import show as show_config
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
      from numpy.core._multiarray_umath import (
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
      raise ImportError(msg)
  ImportError: 
  
  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
  
  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.
  
  We have compiled some common reasons and troubleshooting tips at:
  
      https://numpy.org/devdocs/user/troubleshooting-importerror.html
  
  Please note and check the following:
  
    * The Python version is: Python3.11 from "/tmp/tmprqblgvbd/.venv/bin/python"
    * The NumPy version is: "1.26.4"
  
  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.
  
  Original error was: /tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so: failed to map segment from shared object
  
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/dist-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.11/dist-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
    File "/tmp/tmprqblgvbd/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
      raise ImportError(msg) from e
  ImportError: Error importing numpy: you should not try to import numpy from
          its source directory; please exit the numpy source tree, and relaunch
          your python interpreter from there.
  

  at /usr/local/lib/python3.11/dist-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with insightface (0.7.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "insightface (==0.7.3)"'.

**** cleanup ****
```

```
Starting gunicorn 21.2.0                           
[03/22/24 12:53:58] INFO     Listening at: http://0.0.0.0:3003 (2802)           
[03/22/24 12:53:58] INFO     Using worker: uvicorn.workers.UvicornWorker        
[03/22/24 12:53:58] INFO     Booting worker with pid: 2820                      
[03/22/24 12:53:58] ERROR    Exception in worker process                        
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/arbiter.py:609 in    │
                             │ spawn_worker                                    │
                             │                                                 │
                             │   606 │   │   │   util._setproctitle("worker [% │
                             │   607 │   │   │   self.log.info("Booting worker │
                             │   608 │   │   │   self.cfg.post_fork(self, work │
                             │ ❱ 609 │   │   │   worker.init_process()         │
                             │   610 │   │   │   sys.exit(0)                   │
                             │   611 │   │   except SystemExit:                │
                             │   612 │   │   │   raise                         │
                             │                                                 │
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/workers/base.py:134  │
                             │ in init_process                                 │
                             │                                                 │
                             │   131 │   │   │   self.reloader = reloader_cls( │
                             │   132 │   │   │   │   │   │   │   │   │   │     │
                             │   133 │   │                                     │
                             │ ❱ 134 │   │   self.load_wsgi()                  │
                             │   135 │   │   if self.reloader:                 │
                             │   136 │   │   │   self.reloader.start()         │
                             │   137                                           │
                             │                                                 │
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/workers/base.py:146  │
                             │ in load_wsgi                                    │
                             │                                                 │
                             │   143 │                                         │
                             │   144 │   def load_wsgi(self):                  │
                             │   145 │   │   try:                              │
                             │ ❱ 146 │   │   │   self.wsgi = self.app.wsgi()   │
                             │   147 │   │   except SyntaxError as e:          │
                             │   148 │   │   │   if not self.cfg.reload:       │
                             │   149 │   │   │   │   raise                     │
                             │                                                 │
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/app/base.py:67 in    │
                             │ wsgi                                            │
                             │                                                 │
                             │    64 │                                         │
                             │    65 │   def wsgi(self):                       │
                             │    66 │   │   if self.callable is None:         │
                             │ ❱  67 │   │   │   self.callable = self.load()   │
                             │    68 │   │   return self.callable              │
                             │    69 │                                         │
                             │    70 │   def run(self):                        │
                             │                                                 │
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/app/wsgiapp.py:58 in │
                             │ load                                            │
                             │                                                 │
                             │   55 │   │   if self.cfg.paste is not None:     │
                             │   56 │   │   │   return self.load_pasteapp()    │
                             │   57 │   │   else:                              │
                             │ ❱ 58 │   │   │   return self.load_wsgiapp()     │
                             │   59                                            │
                             │   60                                            │
                             │   61 def run():                                 │
                             │                                                 │
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/app/wsgiapp.py:48 in │
                             │ load_wsgiapp                                    │
                             │                                                 │
                             │   45 │   │   │   │   raise ConfigError("No appl │
                             │   46 │                                          │
                             │   47 │   def load_wsgiapp(self):                │
                             │ ❱ 48 │   │   return util.import_app(self.app_ur │
                             │   49 │                                          │
                             │   50 │   def load_pasteapp(self):               │
                             │   51 │   │   from .pasterapp import get_wsgi_ap │
                             │                                                 │
                             │ /config/machine-learning/cuda/.venv/lib/python3 │
                             │ .11/site-packages/gunicorn/util.py:371 in       │
                             │ import_app                                      │
                             │                                                 │
                             │   368 │   │   module, obj = parts[0], parts[1]  │
                             │   369 │                                         │
                             │   370 │   try:                                  │
                             │ ❱ 371 │   │   mod = importlib.import_module(mod │
                             │   372 │   except ImportError:                   │
                             │   373 │   │   if module.endswith(".py") and os. │
                             │   374 │   │   │   msg = "Failed to find applica │
                             │                                                 │
                             │ /usr/lib/python3.11/importlib/__init__.py:126   │
                             │ in import_module                                │
                             │                                                 │
                             │   123 │   │   │   if character != '.':          │
                             │   124 │   │   │   │   break                     │
                             │   125 │   │   │   level += 1                    │
                             │ ❱ 126 │   return _bootstrap._gcd_import(name[le │
                             │   127                                           │
                             │   128                                           │
                             │   129 _RELOADING = {}                           │
                             │ in _gcd_import:1204                             │
                             │ in _find_and_load:1176                          │
                             │ in _find_and_load_unlocked:1147                 │
                             │ in _load_unlocked:690                           │
                             │ in exec_module:940                              │
                             │ in _call_with_frames_removed:241                │
                             │                                                 │
                             │ /app/immich/machine-learning/app/main.py:18 in  │
                             │ <module>                                        │
                             │                                                 │
                             │    15 from onnxruntime.capi.onnxruntime_pybind1 │
                             │    16 from starlette.formparsers import MultiPa │
                             │    17                                           │
                             │ ❱  18 from app.models.base import InferenceMode │
                             │    19                                           │
                             │    20 from .config import PreloadModelData, log │
                             │    21 from .models.cache import ModelCache      │
                             │                                                 │
                             │ /app/immich/machine-learning/app/models/__init_ │
                             │ _.py:8 in <module>                              │
                             │                                                 │
                             │    5 from .base import InferenceModel           │
                             │    6 from .clip import MCLIPEncoder, OpenCLIPEn │
                             │    7 from .constants import is_insightface, is_ │
                             │ ❱  8 from .facial_recognition import FaceRecogn │
                             │    9                                            │
                             │   10                                            │
                             │   11 def from_model_type(model_type: ModelType, │
                             │      InferenceModel:                            │
                             │                                                 │
                             │ /app/immich/machine-learning/app/models/facial_ │
                             │ recognition.py:6 in <module>                    │
                             │                                                 │
                             │    3                                            │
                             │    4 import cv2                                 │
                             │    5 import numpy as np                         │
                             │ ❱  6 from insightface.model_zoo import ArcFaceO │
                             │    7 from insightface.utils.face_align import n │
                             │    8 from numpy.typing import NDArray           │
                             │    9                                            │
                             ╰─────────────────────────────────────────────────╯
                             ModuleNotFoundError: No module named 'insightface' 
[03/22/24 12:53:58] INFO     Worker exiting (pid: 2820)                         
[03/22/24 12:53:58] ERROR    Worker (pid:2820) exited with code 3               
[03/22/24 12:53:58] ERROR    Shutting down: Master                              
[03/22/24 12:53:58] ERROR    Reason: Worker failed to boot.
```

**Comment by hydazz** [comment]
Are you attempting to manually build the image? wheres the first block of logs from?

**Comment by Nixon506E** [comment]
The issue was that I had the /tmp directory mounted as tmpfs and docker mounts it with noexec permissions (currently being worked on to allow an exec flag). Once that mount was removed the libraries could be built and copied over properly.
