### ISSUE TITLE
Extract Metadata Job Error

### ISSUE THREAD

**Issue by pache71** [imagegenius/docker-immich#355]
Extract Metadata and Sidecar Metadata jobs error out and stop when encountering corrupted and/or missing files.  I have a few images that were corrupt and would cause the jobs to stop. I deleted the files thinking this would resolve the issue but now the jobs still stop with an error of the files missing. Restarting the jobs cause them to instantly fail on the now deleted files. The jobs should skip corrupt/missing files.

```
[Nest] 1507  - 05/13/2024, 3:53:46 PM   ERROR [JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat '/photos/upload/9a5458cc-f735-441f-8733-8fe6b49a95e3/26/79/26799c52-902b-4a6c-bc95-89b80b9b622b.mov'
[Nest] 1507  - 05/13/2024, 3:53:46 PM   ERROR [JobService] Error: ENOENT: no such file or directory, stat '/photos/upload/9a5458cc-f735-441f-8733-8fe6b49a95e3/26/79/26799c52-902b-4a6c-bc95-89b80b9b622b.mov'
    at async Object.stat (node:internal/fs/promises:1029:18)
    at async MetadataService.exifData (/app/immich/server/dist/services/metadata.service.js:377:23)
    at async MetadataService.handleMetadataExtraction (/app/immich/server/dist/services/metadata.service.js:178:36)
    at async /app/immich/server/dist/services/job.service.js:149:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 1507  - 05/13/2024, 3:53:46 PM   ERROR [JobService] Object:
{
  "id": "331754c5-bc8e-4539-bba2-92b75f2eeeb8"
}

[Nest] 1507  - 05/13/2024, 3:58:05 PM   ERROR [JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat '/photos/upload/9a5458cc-f735-441f-8733-8fe6b49a95e3/49/1a/491a7619-a82d-48f3-938d-775bb5921e0e.MOV'
[Nest] 1507  - 05/13/2024, 3:58:05 PM   ERROR [JobService] Error: ENOENT: no such file or directory, stat '/photos/upload/9a5458cc-f735-441f-8733-8fe6b49a95e3/49/1a/491a7619-a82d-48f3-938d-775bb5921e0e.MOV'
    at async Object.stat (node:internal/fs/promises:1029:18)
    at async MetadataService.exifData (/app/immich/server/dist/services/metadata.service.js:377:23)
    at async MetadataService.handleMetadataExtraction (/app/immich/server/dist/services/metadata.service.js:178:36)
    at async /app/immich/server/dist/services/job.service.js:149:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 1507  - 05/13/2024, 3:58:05 PM   ERROR [JobService] Object:
{
  "id": "47aee795-a6ad-4133-93ea-6d5f698f12e8"
}
```

**Comment by hydazz** [comment]
try adding a 'stub' or fake file there (ie touch `/photos/upload/9a5458cc-f735-441f-8733-8fe6b49a95e3/49/1a/491a7619-a82d-48f3-938d-775bb5921e0e.MOV`), or replace it with a valid video, rerun the job then delete it again from the webui
