### ISSUE TITLE
API errors since 1.106.1

### ISSUE THREAD

**Issue by traktuner** [imagegenius/docker-immich#368]
Hello,
since v1.106.1 I get many API errors in the log and also smart search is not working anymore:

```
[Nest] 152  - 06/11/2024, 12:56:22 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed with status 422: Unprocessable Entity
[Nest] 152  - 06/11/2024, 12:56:22 PM   ERROR [Microservices:JobService] Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed with status 422: Unprocessable Entity
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.encodeImage (/app/immich/server/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/app/immich/server/dist/services/smart-info.service.js:86:27)
    at async /app/immich/server/dist/services/job.service.js:148:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 152  - 06/11/2024, 12:56:22 PM   ERROR [Microservices:JobService] Object:
{
  "id": "9097c2d9-66af-4980-b943-cf23ae4da9a3",
  "source": "upload"
}
```
```
[Nest] 175  - 06/11/2024, 12:52:43 PM   ERROR [Api:Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai"}}}' failed with status 422: Unprocessable Entity
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.encodeText (/app/immich/server/dist/repositories/machine-learning.repository.js:47:26)
    at async SearchService.searchSmart (/app/immich/server/dist/services/search.service.js:96:27)~2r9ubn8w] Failed to search smart
[Nest] 175  - 06/11/2024, 12:52:43 PM   ERROR [Api:Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai"}}}' failed with status 422: Unprocessable Entity
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.encodeText (/app/immich/server/dist/repositories/machine-learning.repository.js:47:26)
    at async SearchService.searchSmart (/app/immich/server/dist/services/search.service.js:96:27)~2r9ubn8w] Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai"}}}' failed with status 422: Unprocessable Entity


```

Is this related to the removal of the micro services container (upstream)?

Thank you!

**Comment by traktuner** [comment]
I don't know why, but the problem fixed itself over time ;)
