### ISSUE TITLE
HEIC thumbnails not generating (iOS 18)

### ISSUE THREAD

**Issue by pducharme** [imagegenius/docker-immich#375]
Since couple of versions (can't really tell wich one break that), all my Uploaded photos that are in the HEIC format are not showing up and display the black logo with the generic picture thumbnail.  If I click it, it still doesn't display it, but if I download it, the file downloaded is OK and show the image correctly.

Running Latest, 1.106.4, on UNRAID 6.2.10.

The Docker LOG is showing this (for each image) : 

`[Nest] 1455  - 06/17/2024, 8:57:39 PM   ERROR [Microservices:JobService] Error: Input file has corrupt header: /photos/upload/24ca4cc0-abf9-404c-9050-f64d4720dc43/a5/02/a502336c-d773-4bfb-b238-f194410e1d07.HEIC: bad seek to 2218037
heif: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0)
    at Sharp.toFile (/app/immich/server/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/app/immich/server/dist/repositories/media.repository.js:69:14)
    at MediaService.generateThumbnail (/app/immich/server/dist/services/media.service.js:158:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGeneratePreview (/app/immich/server/dist/services/media.service.js:135:29)
    at async /app/immich/server/dist/services/job.service.js:148:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 1455  - 06/17/2024, 8:57:39 PM   ERROR [Microservices:JobService] Object:
{
  "id": "ac1ba93a-5b65-4a1d-9075-72f7bd049d9a"
}
`

**Comment by martabal** [comment]
Can you share your config ?

**Comment by pducharme** [comment]
Hi, yes.  

Running on Unraid 6.2.10, here is my docker configuration.  I haven't change it since installation a while ago, and just did the Updates once available.
<img width="681" alt="immich_config1" src="https://github.com/imagegenius/docker-immich/assets/1879339/d169a10f-96c1-4e97-bda6-5a6f931c9e76">
<img width="625" alt="immich_config2" src="https://github.com/imagegenius/docker-immich/assets/1879339/a75981db-613b-4a84-9b0e-c2466f0b663d">

**Comment by pducharme** [comment]
Any Update on this issue @martabal ?  Every new version, I just wish that get fix, but it's not.  Still same errors + no Thumbnails or image previews.

**Comment by martabal** [comment]
Are you using ios 18 ?

**Comment by pducharme** [comment]
Yes, but issue started before that.

**Comment by martabal** [comment]
Upstream has the same issue, that's error is caused by a dependency https://github.com/immich-app/immich/issues/10464

**Comment by pducharme** [comment]
I will check when it started to see if it is at the same time. Also, running missing thumbnail jobs doesn’t resolve it as mentioned in the linked thread. If I click on an image that doesn’t have the thumbnail to see it, it still doesn’t have an image. If I download it the file is fine.

**Comment by martabal** [comment]
Runnning that job won't solve your issue until the libheif dependency has fixed that issue

**Comment by pducharme** [comment]
En effet! c'est juste que dans le Thread qui était en réf, quelqu'un disait que la regénération des thumbnails corrigeait le problème.  J'ai essayé plusieurs fois, sans succès.  Mais maintenant je comprend que tant que libheif ne sera pas corrigé, le problème persistera.  Au moins, ma crainte que les images soient perdues n'est plus, puisqu'en téléchargeant, les fichiers sont intacts et s'ouvrent normalement sur Mac ou PC (avec plugin HEIC).

**Comment by martabal** [comment]
(I'mresponding in english so everyone who read that comment can understand the situation)

The solution on that thread is not really clear: Yes, running the "Generate Thumbnails" job will fix your issue, but only after the libheif dependency fixes the issue and releases a new version.

**Comment by martabal** [comment]
The thumbnails generated by Immich are the images you see on your timeline, photos of people or the preview photo. Immich never touches your original photos, which is why downloading and opening photos works as expected.

**Comment by pducharme** [comment]
Good.  I'll wait for the libheif depedencies to be fixed.  Hopefully, it won't take long.
