### ISSUE TITLE
Unraid - Cuda keeps crashing  "No module named 'numpy.compat'"

### ISSUE THREAD

**Issue by joeblack2k** [imagegenius/docker-immich#380]
1. Unraid
2. Nvidia GPU 1660GTX
3. updated nvidia plugin
4. without cuda no problem

No module named 'numpy.compat'

```
`[06/20/24 15:01:55] INFO     Worker exiting (pid: 2913)                         
[06/20/24 15:01:55] ERROR    Worker (pid:2913) exited with code 3               
[06/20/24 15:01:55] ERROR    Shutting down: Master                              
[06/20/24 15:01:55] ERROR    Reason: Worker failed to boot.                     
[06/20/24 15:01:58] INFO     Starting gunicorn 22.0.0                           
[06/20/24 15:01:58] INFO     Listening at: http://0.0.0.0:3003 (2922)           
[06/20/24 15:01:58] INFO     Using worker: uvicorn.workers.UvicornWorker        
[06/20/24 15:01:58] INFO     Booting worker with pid: 2929                      
Traceback (most recent call last):
  File "/config/machine-learning/cuda/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/config/machine-learning/cuda/.venv/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/config/machine-learning/cuda/.venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 72, in <module>
    from . import numerictypes as nt
  File "/config/machine-learning/cuda/.venv/lib/python3.11/site-packages/numpy/core/numerictypes.py", line 105, in <module>
    from ._type_aliases import (
  File "/config/machine-learning/cuda/.venv/lib/python3.11/site-packages/numpy/core/_type_aliases.py", line 20, in <module>
    from numpy.compat import unicode
ModuleNotFoundError: No module named 'numpy.compat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/machine-learning/cuda/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[06/20/24 15:01:58] ERROR    Exception in worker process                        `
```

**Comment by martabal** [comment]
Should be fixed with #392
