### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Hinetane** [imagegenius/docker-immich#402]
log, I don't know how to solve this problem, can anyone help me?
```
Error: write EPIPE
2024-07-08T13:03:05.852375791Z at afterWriteDispatched (node:internal/stream_base_commons:161:15)
2024-07-08T13:03:05.852405249Z at writeGeneric (node:internal/stream_base_commons:152:3)
2024-07-08T13:03:05.852425958Z at Socket._writeGeneric (node:net:953:11)
2024-07-08T13:03:05.852444624Z at Socket._write (node:net:965:8)
2024-07-08T13:03:05.852462999Z at writeOrBuffer (node:internal/streams/writable:564:12)
2024-07-08T13:03:05.852481374Z at _write (node:internal/streams/writable:493:10)
2024-07-08T13:03:05.852499458Z at Writable.write (node:internal/streams/writable:502:10)
2024-07-08T13:03:05.852517541Z at EventEmitter.sendCommand (/app/immich/server/node_modules/ioredis/built/Redis.js:394:29)
2024-07-08T13:03:05.852537083Z at EventEmitter.info (/app/immich/server/node_modules/ioredis/built/utils/Commander.js:90:25)
2024-07-08T13:03:05.852556041Z at EventEmitter._readyCheck (/app/immich/server/node_modules/ioredis/built/Redis.js:652:14) {
2024-07-08T13:03:05.852575291Z errno: -32,
2024-07-08T13:03:05.852592499Z code: 'EPIPE',
2024-07-08T13:03:05.852609708Z syscall: 'write'
```

**Comment by hydazz** [comment]
what issues are you encountering? What are you doing to cause that error to popup?
