### ISSUE TITLE
Immich container not booting after latest update.  ERROR [Api:An instance of SystemConfigDto has failed the validation:  - property server.externalDomain has failed the following constraints: isUrl  ] Validation error TypeError: Invalid URL

### ISSUE THREAD

**Issue by brun0ls** [imagegenius/docker-immich#441]
Hello guys.

I need you help. Only you guys can help me. You're my only hope!

I'm using imagegenius container in my UNRAID server, thanks to space invader one video.

After the newest update, my container doesn't work anymore.

That's the error:

Starting api worker
[Nest] 1670  - 09/29/2024, 3:29:22 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 1670  - 09/29/2024, 3:29:22 PM   ERROR [Api:An instance of SystemConfigDto has failed the validation:
 - property server.externalDomain has failed the following constraints: isUrl 
] Validation error
TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at SystemConfigCore.buildConfig (/app/immich/server/dist/cores/system-config.core.js:136:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/cores/system-config.core.js:80:35 {
  code: 'ERR_INVALID_URL',
  input: 'taquaras.uk.to'
}
api worker exited with code 1
Starting api worker

Yes, taquaras.uk.to was the address I set in the webgui.

How can I edit the settings to fix this? I can't reach any config/I don't know how to locate it.

Thanks in advance, I will be very grateful for any help.

**Comment by brun0ls** [comment]
> see #438

Thanyou so much friend! That fixed my issue! I searched about it before posting but I really couldn't find! Thanks again!
