### ISSUE TITLE
Container stucked on v1.115.0-ig327

### ISSUE THREAD

**Issue by DemonAngeX2** [imagegenius/docker-immich#452]
Hello, on Unraid docker container, i'm stuck on the version v1.115.0-ig327.
After, immich webui won't start

Here you have the logs: 
```
`       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 99
  User GID: 100
╚═══════════════════════════════╝
[custom-init] No custom files found, skipping...
Starting api worker
[Nest] 211  - 10/19/2024, 6:22:11 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 211  - 10/19/2024, 6:22:11 PM   ERROR [Api:An instance of SystemConfigDto has failed the validation:
 - property server.externalDomain has failed the following constraints: isUrl 
] Validation error
TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at buildConfig (/app/immich/server/dist/utils/config.js:116:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/utils/config.js:53:26 {
  code: 'ERR_INVALID_URL',
  input: 'photos.domainname.fr'
}
api worker exited with code 1
```
I tried to add a variable with URL but it didn't worked.
Can you help me with this error please ? Thank you :)

**Comment by DemonAngeX2** [comment]
Hello,

It remove the URL in server settings and update worked for me. Ty :)
