### ISSUE TITLE
Does this mean something bad?

### ISSUE THREAD

**Issue by blaine07** [imagegenius/docker-immich#70]
```
Error: connect ECONNREFUSED 127.0.0.1:3003
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[Nest] 878  - 04/30/2023, 8:30:43 AM   ERROR [SmartInfoService] Unable to run image tagging pipeline: e2e3cbc2-2e9b-409e-9707-d0557d52ef44
Error: connect ECONNREFUSED 127.0.0.1:3003
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[Nest] 878  - 04/30/2023, 8:30:43 AM   ERROR [SmartInfoService] Unable run object detection pipeline: e2e3cbc2-2e9b-409e-9707-d0557d52ef44
Error: connect ECONNREFUSED 127.0.0.1:3003
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[Nest] 878  - 04/30/2023, 8:30:43 AM   ERROR [SmartInfoService] Unable run clip encoding pipeline: e2e3cbc2-2e9b-409e-9707-d0557d52ef44
``` 

Have I done something wrong here? do  I need to be concerned about whatever this is?

**Comment by martabal** [comment]
These logs mean your machine learning is not running. Can you provide more details about your docker-compose file and about your hardware ?

**Comment by blaine07** [comment]
It's a Dell T710 that doesn't support machine learning - if I remember it's because it doesn't support AVX or something. There was/is a dependency for Machine Learning the hardware doesn't support. Immich is running on/in Unraid.

```
docker run
  -d
  --name='immich-aio'
  --net='proxynet'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="immich-aio"
  -e 'DB_HOSTNAME'='XXXX'
  -e 'DB_USERNAME'='immich1'
  -e 'DB_PORT'='5432'
  -e 'DB_PASSWORD'='XXXX'
  -e 'DB_DATABASE_NAME'='immich1'
  -e 'REDIS_HOSTNAME'='XXXX'
  -e 'REDIS_PORT'='6382'
  -e 'REDIS_PASSWORD'='XXXXXXXX'
  -e 'JWT_SECRET'='REDACTED'
  -e 'DISABLE_MACHINE_LEANRNING'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/CorneliousJD/Docker-Templates/master/icons/immich.png'
  -p '8387:8080/tcp'
  -v '/mnt/user/immich/':'/photos':'rw'
  -v '/mnt/user/appdata/immich/transformers':'/config/transformers':'rw' 'ghcr.io/imagegenius/immich:latest'
88f941be901096fabeac1231195251a3c183c42742cd48f80ee4bef6ed13760a``` 

I may have figured it out. Was using "imagegenius/immich:noml" so changed to "ghcr.io/imagegenius/immich:latest" and inserted the "DISABLE_MACHINE_LEARNING" variable "false".

That *may* have fixed it. Will watch logs for a few.

**Comment by martabal** [comment]
Machine-learning do not require AVX, but search with typesense do. Yep could have fixed it.

**Comment by blaine07** [comment]
> Machine-learning do not require AVX, but search with typesense do. Yep could have fixed it.

Since I know my machine, T710, does NOT support AVX should I just save myself the trouble and siable typesense with ENV too?

**Comment by martabal** [comment]
Yep you can with `DISABLE_TYPESENSE=true`

**Comment by blaine07** [comment]
> Yep you can with `DISABLE_TYPESENSE=true`

Yes, I will disable. 

Also, still seeing this in logs:

```
[Nest] 154  - 04/30/2023, 10:42:44 AM   ERROR [ExceptionsHandler] timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/app/immich/server/node_modules/pg-pool/index.js:200:27)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[Nest] 154  - 04/30/2023, 10:42:44 AM   ERROR [ExceptionsHandler] timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/app/immich/server/node_modules/pg-pool/index.js:200:27)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[Nest] 154  - 04/30/2023, 11:37:04 AM   ERROR [ExpressAdapter] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.onclose (node:internal/streams/end-of-stream:145:30)
    at ServerResponse.emit (node:events:525:35)
    at Socket.onServerResponseClose (node:_http_server:275:23)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:301:12)
```

**Comment by martabal** [comment]
It's "normal". You get these errors from hovering/playing video on the web.

**Comment by martabal** [comment]
Is it solved ? By the way, you can use the noml version which is a lightweight version with typesense and machine-learning disabled.
