### ISSUE TITLE
Fails to start server - statfs is not a function

### ISSUE THREAD

**Issue by mahood73** [imagegenius/docker-immich#82]
I just installed the image on Unraid, including the Docker Mods for Postgres and Redis.

It boots, I can log in, but the server is not running (shows in the GUI as 'Server Status: Offline'. In the log files I see this error repeatedly:

`[Nest] 1949  - 05/19/2023, 11:20:35 AM   ERROR [ExceptionsHandler] promises_1.default.statfs is not a function
TypeError: promises_1.default.statfs is not a function
    at FilesystemProvider.checkDiskUsage (/app/immich/server/dist/apps/immich/libs/infra/src/repositories/filesystem.provider.js:64:48)
    at ServerInfoService.getInfo (/app/immich/server/dist/apps/immich/libs/domain/src/server-info/server-info.service.js:28:55)
    at ServerInfoController.getServerInfo (/app/immich/server/dist/apps/immich/apps/immich/src/controllers/server-info.controller.js:24:29)
    at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/app/immich/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/immich/server/node_modules/@nestjs/core/router/router-proxy.js:9:17`

**Comment by martabal** [comment]
#81 fixes it

**Comment by mahood73** [comment]
Ah, looks like it was already known, but not in an issue here:
https://github.com/immich-app/immich/issues/2477

Should be fixed by PR #81 

For now, downgrading by pulling image: immich:1.56.0 seems to be a workaround.

**Comment by hydazz** [comment]
fixed in latest build :)
