### ISSUE TITLE
Keep getting a promises_1.default.statfs is not a function Error

### ISSUE THREAD

**Issue by Rohit22014** [imagegenius/docker-immich#83]
Hi I have this container setup, everything runs fine except the total storage and the server status shows offline and I keep getting this error in the logs. I checked this error online and could be related to node.js. No idea how to fix this. Any help would be appreciated!

 

[Nest] 1876 - 05/19/2023, 4:31:15 AM ERROR [ExceptionsHandler] promises_1.default.statfs is not a function

05/19/2023 12:31:15 PM

TypeError: promises_1.default.statfs is not a function

05/19/2023 12:31:15 PM

at FilesystemProvider.checkDiskUsage (/app/immich/server/dist/apps/immich/libs/infra/src/repositories/filesystem.provider.js:64:48)

05/19/2023 12:31:15 PM

at ServerInfoService.getInfo (/app/immich/server/dist/apps/immich/libs/domain/src/server-info/server-info.service.js:28:55)

05/19/2023 12:31:15 PM

at ServerInfoController.getServerInfo (/app/immich/server/dist/apps/immich/apps/immich/src/controllers/server-info.controller.js:24:29)

05/19/2023 12:31:15 PM

at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:38:29

05/19/2023 12:31:15 PM

at InterceptorsConsumer.intercept (/app/immich/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)

05/19/2023 12:31:15 PM

at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:46:60

05/19/2023 12:31:15 PM

at runMicrotasks (<anonymous>)

05/19/2023 12:31:15 PM

at processTicksAndRejections (node:internal/process/task_queues:96:5)

05/19/2023 12:31:15 PM

at async /app/immich/server/node_modules/@nestjs/core/router/router-proxy.js:9:17

**Comment by hydazz** [comment]
this will be fixed in a moment :)
https://github.com/imagegenius/docker-immich/issues/82
